Repository yukinarit/pyserde, pull requests merged in 2023-05, with the labels that each got.

#341 Update docs
  docs/getting-started.md
  docs/introduction.md
Labels: documentation

#342 Fix dataclass with recursive containers
  .pre-commit-config.yaml
  CONTRIBUTING.md
  examples/recursive_list.py
  examples/runner.py
  serde/compat.py
  setup.cfg
  tests/common.py
  tests/data.py
Labels: bug

#345 Fix recursive union
  examples/recursive_union.py
  examples/runner.py
  serde/de.py
  serde/se.py
Labels: bug

#346 Refactor to have more explicit type
  serde/core.py
  serde/de.py
  serde/inspect.py
  serde/msgpack.py
Labels: refactoring

#349 Fix typo in union.md
  docs/features/union.md
Labels: documentation

#348 Fix type error when calling serde as function
  serde/__init__.py
  serde/inspect.py
Labels: bug

#357 Remove webapi example
  examples/webapi/README.md
  examples/webapi/app.py
  examples/webapi/pyproject.toml
Labels: example

#359 Fix mypy error for flatten attribute
  serde/core.py
Labels: bug
