Repository yukinarit/pyserde, pull requests merged in 2023-02, with the labels that each got.

#303 feat: Support optional ClassVar serialization
  README.md
  docs/introduction.md
  docs/supported-types.md
  examples/class_var.py
  examples/runner.py
  serde/__init__.py
  serde/compat.py
  serde/core.py
  serde/se.py
  tests/test_basics.py
Labels: enhancement

#304 Add .github/release.yml
  .github/release.yml
Labels: ci

#305 Update CI scripts
  .github/release.yml
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ci

#306 Upgrade to setup-python@v4 and enable caching
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ci

#307 Upgrade codecov-action to v3
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: ci

#310 Publish with Github Actions
  .github/workflows/publish.yml
  pyproject.toml
Labels: ci

#311 Migrate to Github's changelog
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  docs/SUMMARY.md
Labels: documentation

#315 Allow serializing and deserializing root dataclasses
  serde/de.py
  serde/se.py
  tests/test_basics.py
Labels: enhancement

#313 Fix deserialization with NewType and Untagged Union
  serde/de.py
  serde/se.py
  tests/test_union.py
Labels: bug

#316 Set commit author and title for commits in gh-pages
  .github/workflows/build.yml
  serde/se.py
Labels: ci

#317 Update contributors
  .all-contributorsrc
  README.md
Labels: documentation

#319 Document (de)serializing dataclasses without @serde
  docs/features/decorators.md
  examples/plain_dataclass.py
  examples/plain_dataclass_class_attribute.py
  examples/runner.py
Labels: documentation

#320 s/0.9.10/0.10.0/
  docs/features/decorators.md
  examples/plain_dataclass.py
Labels: ignore-for-release
