Repository yukinarit/pyserde, pull requests merged in 2023-07, with the labels that each got.

#403 Fix mypy/pyright errors in serde/compat.py
  pyproject.toml
  serde/compat.py
Labels: refactoring

#339 Union directly
  docs/en/union.md
  examples/runner.py
  examples/union_directly.py
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/json.py
  serde/msgpack.py
  serde/pickle.py
  serde/se.py
  serde/toml.py
  serde/yaml.py
  tests/test_union.py
Labels: enhancement, breaking-change

#405 Temporarily remove outdated benchmark doc
  docs/en/SUMMARY.md
  docs/en/benchmark.md
Labels: documentation

#406 Fix mypy/pyright errors in serde/core.py
  pyproject.toml
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/se.py
Labels: refactoring

#408 Do not import optional modules in __init__.py
  serde/__init__.py
Labels: bug

#412 Fix frozen dataclass inheritance
  serde/core.py
  tests/test_basics.py
Labels: bug

#413 Add support for dataclasses with `kw_only`
  serde/core.py
  serde/de.py
  tests/test_kwonly.py
Labels: enhancement

#415 Document dataclass `frozen` and `kw_only` support
  docs/en/class-attributes.md
  examples/kw_only.py
  examples/runner.py
Labels: documentation

#416 Do not shallow clone when publishing to PyPI
  .github/workflows/publish.yml
Labels: build

#417 Add prerelease job to make sure version is correct
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: ci

#419 Fix fetch-depth
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: ci

#420 Fix mypy/pyright errors in serde/se.py
  pyproject.toml
  serde/compat.py
  serde/core.py
  serde/se.py
Labels: refactoring
