Repository yukinarit/pyserde, pull requests merged in 2023-03, with the labels that each got.

#321 Fix variable length of tuple
  examples/runner.py
  examples/variable_length_tuple.py
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/se.py
  tests/common.py
  tests/test_basics.py
  tests/test_compat.py
Labels: bug

#322 Fix more type errors
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/se.py
Labels: refactoring

#327 Update README.md
  README.md
Labels: documentation

#331 fix: Fixed broken strict type checking for Optionals. Fixes #330
  serde/core.py
Labels: bug

#332 :busts_in_silhouette: Add @Fredrik-Reinholdsen as a contributor
  .all-contributorsrc
  README.md
Labels: documentation

#334 Do not render field with init=False
  serde/core.py
  serde/de.py
  tests/common.py
  tests/data.py
Labels: enhancement
