Repository yukinarit/pyserde, pull requests merged in 2023-06, with the labels that each got.

#354 Fix combination of alias and default
  serde/de.py
  tests/test_basics.py
Labels: bug

#367 More strong typing on (de)serialize APIs
  .pre-commit-config.yaml
  pyproject.toml
  serde/de.py
  serde/json.py
  serde/msgpack.py
  serde/pickle.py
  serde/se.py
  serde/toml.py
  serde/yaml.py
Labels: enhancement

#371 Fix mypy error for Optional and Union in (de)serialize APIs
  serde/de.py
  serde/json.py
  serde/msgpack.py
  serde/pickle.py
  serde/toml.py
  serde/yaml.py
Labels: bug

#374 Fix expired links in README
  README.md
  docs/en/decorators.md
  serde/__init__.py
  serde/compat.py
  serde/se.py
Labels: documentation

#377 Fix nested generic class deserialization
  serde/compat.py
  serde/core.py
  serde/de.py
  tests/common.py
  tests/test_compat.py
Labels: bug

#382 Ignore @overload in code coverage
  .coveragerc
  pyproject.toml
Labels: build

#385 Make serde.core.Field a generic type
  bench/bench.py
  pyproject.toml
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/se.py
Labels: refactoring

#387 Fix a bit more mypy error
  serde/compat.py
  serde/core.py
  serde/de.py
Labels: refactoring

#389 Fix deserializing from incompatible value e.g. None
  serde/de.py
  tests/test_basics.py
  tests/test_de.py
Labels: bug

#388 Support (de)serialize a subclass of primitive type
  examples/primitive_subclass.py
  examples/runner.py
  serde/compat.py
  serde/de.py
  tests/common.py
  tests/data.py
Labels: enhancement

#401 Fix mypy/pyright errors in serde/inspect.py
  pyproject.toml
  serde/inspect.py
Labels: refactoring
