Repository yukinarit/pyserde, pull requests merged in 2024-03, with the labels that each got.

#482 skip conversion if the object is already the correct type
  serde/de.py
Labels: enhancement

#484 :busts_in_silhouette: Add @uyha as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#486 Fix reuse_instances for non dataclass objects
  serde/core.py
  serde/json.py
  serde/msgpack.py
  serde/pickle.py
  serde/se.py
  serde/toml.py
  serde/yaml.py
  tests/test_basics.py
Labels: bug

#487 Don't implement beartype for dataclass without serde
  serde/de.py
  serde/se.py
  tests/test_type_check.py
Labels: breaking-change

#488 Create dependabot.yml
  .github/dependabot.yml
Labels: build

#489 Update dependabot.yml
  .github/dependabot.yml
Labels: build

#485 prefer `is_bearable` to `isinstance`
  serde/se.py
Labels: bug

#497 Fix mypy type errors in tests
  pyproject.toml
  tests/common.py
  tests/test_de.py
Labels: test

#498 :busts_in_silhouette: Add @rtbs-dev as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#502 Update black to 24.3.0
  .pre-commit-config.yaml
  bench/bench.py
  examples/jsonfile.py
  examples/rename_all.py
  examples/tomlfile.py
  examples/yamlfile.py
  serde/__init__.py
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/inspect.py
  serde/json.py
  serde/msgpack.py
  serde/pickle.py
  serde/toml.py
  serde/yaml.py
  tests/test_custom.py
  tests/test_legacy_custom.py
Labels: build

#504 Raises SerdeError when type validation fails
  serde/de.py
  serde/se.py
  tests/test_beartype.py
Labels: enhancement

#505 Use latest python feature in serde/examples
  .github/workflows/build.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  examples/default_dict.py
  examples/generics_pep695.py
  examples/init_var.py
  examples/jsonfile.py
  examples/recursive.py
  examples/recursive_union.py
  examples/rename_all.py
  examples/runner.py
  examples/tomlfile.py
  examples/type_check_coerce.py
  examples/union.py
  examples/union_directly.py
  examples/union_operator.py
  examples/union_tagging.py
  examples/yamlfile.py
  pyproject.toml
  tests/common.py
  tests/test_basics.py
  tests/test_legacy_custom.py
  tests/test_union.py
Labels: example

#506 Custom validation error requires beartype 0.17
  pyproject.toml
Labels: build

#507 Publish gh-pages when github release is made
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: ci
