Repository yukinarit/pyserde, pull requests merged in 2024-04, with the labels that each got.

#509 Handle empty tuple more properly
  pyproject.toml
  serde/core.py
  tests/test_compat.py
Labels: refactoring

#510 Refactor tests
  pyproject.toml
  tests/common.py
  tests/test_compat.py
  tests/test_de.py
  tests/test_se.py
  tests/test_type_check.py
  tests/test_union.py
Labels: refactoring

#511 add some examples
  docs/en/types.md
  examples/runner.py
  examples/type_ipaddress.py
  examples/type_numpy.py
  examples/type_pathlib.py
  examples/type_uuid.py
  pyproject.toml
Labels: example

#519 Fix pathlib serialization
  serde/compat.py
Labels: bug

#522 👥 Add @JWSong as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release
