Repository yukinarit/pyserde, pull requests merged in 2024-02, with the labels that each got.

#470 Pin version of plum-dispatch as v2.3 breaks custom class serializer
  pyproject.toml
Labels: build

#471 Allow bytes in from_json typing
  CONTRIBUTING.md
  serde/json.py
Labels: enhancement

#474 :busts_in_silhouette: Add @davetapley as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#476 pyserde is powered by beartype
  .pre-commit-config.yaml
  docs/en/SUMMARY.md
  docs/en/decorators.md
  docs/en/type-check.md
  examples/enum34.py
  examples/forward_reference.py
  examples/generics_nested.py
  examples/init_var.py
  examples/runner.py
  examples/type_check_coerce.py
  examples/type_check_disabled.py
  examples/type_check_strict.py
  pyproject.toml
  serde/__init__.py
  serde/compat.py
  serde/core.py
  serde/de.py
  serde/json.py
  serde/msgpack.py
  serde/numpy.py
  serde/pickle.py
  serde/se.py
  serde/toml.py
  serde/yaml.py
  tests/common.py
  tests/data.py
  tests/test_basics.py
  tests/test_compat.py
  tests/test_custom.py
  tests/test_de.py
  tests/test_flatten.py
  tests/test_kwonly.py
  tests/test_lazy_type_evaluation.py
  tests/test_legacy_custom.py
  tests/test_literal.py
  tests/test_numpy.py
  tests/test_se.py
  tests/test_type_check.py
  tests/test_union.py
Labels: breaking-change

#479 Fix syntax error in type-check.md
  docs/en/type-check.md
Labels: documentation
