Repository yukinarit/pyserde, pull requests merged in 2024-06, with the labels that each got.

#537 Add monthly downloads badge to README
  README.md
Labels: documentation

#538 Cache more code template to speed up @serde codegen
  serde/de.py
Labels: performance

#540 👥 Add @Aman-Clement as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#542 Fix flatten for optional
  serde/de.py
  serde/se.py
  tests/test_flatten.py
Labels: bug

#546 Fix mdbook edit-url-template
  docs/en/book.toml
  docs/ja/book.toml
Labels: documentation

#547 Update README and introduction
  README.md
  docs/en/introduction.md
  docs/ja/introduction.md
Labels: documentation

#548 Update documentation of from_dict/to_dict
  README.md
  docs/en/data-formats.md
  docs/en/getting-started.md
  serde/se.py
Labels: documentation

#551 Translate data-formats.md to Japanese
  docs/ja/data-formats.md
Labels: documentation

#552 👥 Add @K-dash as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#557 pyserde does not support numpy 2 yet
  pyproject.toml
Labels: build

#555 Translate decorators.md to Japanese
  docs/ja/decorators.md
Labels: documentation

#554 Translate types.md to Japanese
  docs/en/types.md
  docs/ja/types.md
Labels: documentation

#560 Translate type-check.md, extension.md, and faq.md to Japanese
  docs/ja/extension.md
  docs/ja/faq.md
  docs/ja/type-check.md
Labels: documentation

#561 Fix Union deserialization with different ordering
  serde/compat.py
  tests/test_union.py
Labels: bug

#565 Fix deserialization when internal tagging is used for non dataclass
  serde/compat.py
  serde/de.py
  tests/test_compat.py
  tests/test_union.py
Labels: bug
