Repository yukinarit/pyserde, pull requests merged in 2024-05, with the labels that each got.

#518 feat: add support for SQLAlchemy dataclass-mapped tables
  .github/workflows/test.yml
  README.md
  docs/en/types.md
  examples/runner.py
  examples/type_sqlalchemy.py
  pyproject.toml
  serde/compat.py
  serde/sqlalchemy.py
  tests/test_sqlalchemy.py
Labels: enhancement

#527 👥 Add @barsa-net as a contributor
  .all-contributorsrc
  README.md
Labels: ignore-for-release

#531 Remove @dataclass from documentation
  docs/en/class-attributes.md
  docs/en/decorators.md
  docs/en/introduction.md
  docs/en/type-check.md
  docs/en/union.md
Labels: documentation
