Repository yukinarit/pyserde, pull requests merged in 2024-12, with the labels that each got.

#616 Fix to_dict docs output
  docs/en/data-formats.md
  docs/ja/data-formats.md
Labels: documentation

#618 Fix dict[str, Any] serialization
  serde/se.py
  tests/test_basics.py
Labels: bug

#620 Fix render_tuple with coerce
  serde/de.py
  serde/se.py
  tests/test_de.py
  tests/test_type_check.py
Labels: bug

#622 Support pep695 type alias
  README.md
  conftest.py
  examples/runner.py
  examples/type_alias_pep695.py
  serde/compat.py
  serde/de.py
  serde/se.py
  tests/test_type_alias.py
Labels: enhancement

#627 Fix spelling of object.
  serde/yaml.py
Labels: documentation
